let wrong_amount = "WRONG_AMOUNT"
let unknown_view_get_balance = "UNKNOWN_VIEW_GET_BALANCE"
let ins_balance = "INS_BALANCE"
let unknown_fa2_contract = "UNKNOWN_FA2_CONTRACT"
let not_owner = "NOT_OWNER"
let unknown_proposal = "UNKNOWN_PROPOSAL"
let proposal_not_active = "PROPOSAL_NOT_ACTIVE"
let unknown_transfer_destination = "UNKNOWN_TRANSFER_DESTINATION"
